# Generated by Django 3.2.20 on 2023-10-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='date_updated_edited',
            new_name='last_edited',
        ),
    ]
