# Generated by Django 3.2.20 on 2023-10-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_date_updated_edited_notes_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
