# Generated by Django 3.2.20 on 2023-10-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
